name: bankak_app
description: تطبيق بنكك - محاكاة تحويلات بنك الخرطوم
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  gal: ^2.3.0
  permission_handler: ^11.3.1
  screenshot: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
